var themes = [
  {
    'theme-name': 'modern ink',
    'background': '#fff',
    'selection-text': '#fff',
    'selection-bg': '#fc1c0e',
    'text': '#000',
    'color2': '#8b8b8b',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#fc1c0e',
    'command': '#fc1c0e',
    'command-glow': '#fc0e4e',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '0px',
    'link': '#c8763b',
    'white': '#fff',
  },
  {
    'theme-name': 'rose pine moon',
    'background': '#1f1c30',
    'selection-text': '#1f1c30',
    'selection-bg': '#b692e2',
    'text': '#b692e2',
    'color2': '#d9d5f1',
    'error': '#f1f1d5',
    'index': '#DCDCCC',
    'cursor': '#b692e2',
    'command': '#de89be',
    'command-glow': '#e292c311',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '0px',
    'link': '#fff7b9',
    'white': '#fff',
  },
  {
    'theme-name': 'pink blue boogaloo',
    'background': '#fff',
    'selection-text': '#fff',
    'selection-bg': '#fc1c0e',
    'text': '#000',
    'color2': '#8b8b8b',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#f044a5',
    'command': '#f044a5',
    'command-glow': '#fc0e4e',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '0px',
    'link': '#2e99d9',
    'white': '#fff',
  },
  {
    'theme-name': 'blue dolphin',
    'background': '#052b3f',
    'selection-text': '#052b3f',
    'selection-bg': '#1cdffe',
    'text': '#1cdffe',
    'color2': '#fff',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#fdc0fa',
    'command': '#fdc0fa',
    'command-glow': '#f6d3f4',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '0px',
    'link': '#fdc0fa',
    'white': '#fff',
  },
];