var themes = [
    {
      'theme-name': 'modern ink',
      'background': '#fff',
      'selection-text': '#fff',
      'selection-bg': '#080892',
      'text': '#000',
      'color2': '#8b8b8b',
      'error': '#fa5075',
      'index': '#DCDCCC',
      'cursor': '#fc1c0e',
      'command': '#fc1c0e',
      'command-glow': '#fc0e4e',
      'command-glow-x': '0px',
      'command-glow-y': '0px',
      'command-glow-r': '0px',
      'link': '#585be2',
      'white': '#fff',
    },
    {
      'theme-name': 'blue dolphin',
      'background': '#052b3f',
      'selection-text': '#052b3f',
      'selection-bg': '#1cdffe',
      'text': '#1cdffe',
      'color2': '#fff',
      'error': '#fa5075',
      'index': '#DCDCCC',
      'cursor': '#fdc0fa',
      'command': '#fdc0fa',
      'command-glow': '#f6d3f4',
      'command-glow-x': '0px',
      'command-glow-y': '0px',
      'command-glow-r': '0px',
      'link': '#fdc0fa',
      'white': '#fff',
    },
  ];