var themes = [
  {
    'theme-name': 'rose pink blue boogaloo',
    'background': '#fff',
    'selection-text': '#fff',
    'selection-bg': '#2e99d9',
    'text': '#000',
    'color2': '#8b8b8b',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#fd3c3c',
    'command': '#fd3c3c',
    'command-glow': '#fd3c3c50',
    'glow-x': '0px',
    'glow-y': '0px',
    'glow-r': '5px',
    'link': '#2e99d9',
    'link-glow': '#2e99d950',
    'white': '#fff',
  },
  {
    'theme-name': 'retro',
    'background': '#000',
    'selection-text': '#000',
    'selection-bg': '#00f61f',
    'text': '#00f61f',
    'color2': '#8b8b8b',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#00f61f',
    'command': '#00f61f',
    'command-glow': '#00f61fDD',
    'glow-x': '0px',
    'glow-y': '0px',
    'glow-r': '5px',
    'link': '#00f61f',
    'link-glow': '#00f61fAA',
    'white': '#fff',
  },
  {
    'theme-name': 'rose pine moon',
    'background': '#1f1c30',
    'selection-text': '#1f1c30',
    'selection-bg': '#b692e2',
    'text': '#b692e2',
    'color2': '#d9d5f1',
    'error': '#f1f1d5',
    'index': '#DCDCCC',
    'cursor': '#de89be',
    'command': '#de89be',
    'command-glow': '#de89beB3',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '5px',
    'link': '#fff7b9',
    'link-glow': '#fff7b980',
    'white': '#fff',
  },
  {
    'theme-name': 'modern ink',
    'background': '#fff',
    'selection-text': '#fff',
    'selection-bg': '#fc1c0e',
    'text': '#000',
    'color2': '#8b8b8b',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#fc1c0e',
    'command': '#fc1c0e',
    'command-glow': '#fc1c0e60',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '5px',
    'link': '#c8763b',
    'link-glow': '#c8763b40',
    'white': '#fff',
  },
  {
    'theme-name': 'blue dolphin',
    'background': '#052b3f',
    'selection-text': '#052b3f',
    'selection-bg': '#1cdffe',
    'text': '#1cdffe',
    'color2': '#fff',
    'error': '#fa5075',
    'index': '#DCDCCC',
    'cursor': '#fdc0fa',
    'command': '#fdc0fa',
    'command-glow': '#fdc0faB3',
    'command-glow-x': '0px',
    'command-glow-y': '0px',
    'command-glow-r': '5px',
    'link': '#fdc0fa',
    'link-glow': '#fdc0faB3',
    'white': '#fff',
  },
];